#ETL Pipeline
name: github action demo pipeline

on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: run extract.py
        run: python extract.py
  transform-data:
    runs-on: ubuntu-latest
    needs: extract-data
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: run transform.py
        run: python transform.py
  load-data:
    runs-on: checkout code
    needs: transform-data
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: run load.py
        run: python load.py